### PR TITLE
Updated and extended terms

### PR DESCRIPTION
**Pull request by the-real-grinny**
I found this on Neocities somehow. I made some changes to the definitions of the license that felt like they made sense. Looks like a cool concept either way.

### CODE REVIEW

**Review by craftnut — CHANGES_REQUESTED** [review]
Line 39 is talking about software licensed under Helium, maybe we can swap some words out to make the line more generic so developers can explain a lack of provided warranty for their software? Just a thought I had.

**Comment by the-real-grinny** [comment]
Take a look at the additional things I added on. Hopefully that spells it out more plainly for developers while leaving the door open in regard to acceptable use as defined by the earlier terms.

**Review by craftnut — APPROVED** [review]
Extended terms approved. I appreciate the assistance on clarifying certain things, worded it better than I could have.
Thanks!

**Comment by the-real-grinny** [comment]
I'm happy to help! Was fun to get a little technical. Best of luck!

**Pull request merged**
